# docker-compose.yml

version: '3.9'

services:
  # The Redis Service
  redis:
    image: "redis:alpine"
    restart: always

  # The Django App Service
  app:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: "daphne -b 0.0.0.0 -p 8000 pothole_project_django.asgi:application"
    depends_on:
      - redis